const promptDatabase = [
    {
    "title": "FEMME PORTRAIT FASHION",
    "styles": "femme portrait fashion",
    "img": [
        "Images/IMG_20260329_215803.png"
    ],
    "prompt": "Créez un portrait hyperréaliste et de grande qualité d'une femme en gros plan, de profil par-dessus l'épaule, peau lisse en porcelaine, le regard expressif tourné vers l'objectif ; cheveux rassemblés en un chignon négligé avec des mèches rebelles, maquillage naturel et lumineux mettant l'accent sur les lèvres et les sourcils ; accessoires — lunettes élégantes à monture métallique fine et verres dégradés rouge-orange, boucles d'oreilles, plusieurs piercings à l'oreille ; vêtements — casquette olive avec une chaîne décorative, veste légère tombant sur l'épaule, dévoilant la clavicule ; composition — grand portrait, mise au point sur le visage et les accessoires, arrière-plan clair et artistique avec une texture et un dégradé doux ; Éclairage : lumière de studio chaude et douce avec un léger effet de contre-jour, soulignant la texture de la peau et la profondeur des couleurs, ombres fluides ; Photoréalisme, ultra-détail (8K), profondeur de champ (f/1,8), éclairage cinématographique, retouche professionnelle, teintes chaudes et saturées, haute netteté, HDR, grain léger, style beauté éditorial de mode.\nImage ratio : 2/3."
},
    {
    "title": "FEMME FASHION ROYALE GOTHIQUE",
    "styles": "femme fashion",
    "img": [
        "Images/IMG_20260329_214923.png"
    ],
    "prompt": "Créez une photographie cinématographique ultra-réaliste d’une femme royale, utilisez la photo jointe comme figure de référence debout dans un cadre gothique et atmosphérique. Elle porte un corset ressemblant à une armure noire métallisée finement détaillée avec des ornements en épine et un décolleté plongeant, associé à des manches longues assorties qui s’étendent dans des épaulettes sculptées ressemblant à des branches tordues. Le corset révèle un clivage et se connecte à une armure de cuisse haute avec des motifs en filigrane organiques ressemblant à de la dentelle, exposant une fente haute dans une cape en velours rouge et noir fluide qui drape de manière spectaculaire jusqu’au sol. Sa tête est couronnée d’une couronne argentée à pointes avec des extensions pointues, semblables à des brindilles et une pierre précieuse centrale de couleur turquoise ; un bijou de couleur turquoise assorti orne la pièce de poitrine. La peau du modèle est impeccable, avec un éclairage naturel mettant en valeur les textures de l’armure et du tissu. L’arrière-plan est un intérieur fantaisiste sombre et lunatique avec des tons bleus verts atténués, un cadrage doré orné et une profondeur atmosphérique, concentrant le regard du spectateur sur la présence imposante du sujet et les textures hyper-détaillées du costume. Capturez la scène avec une haute résolution, une qualité de film de 35 mm, un focus précis sur l’expression du visage et les détails matériels, ainsi qu’un éclairage en clair-obscur dramatique qui met l’accent sur le contraste entre l’armure métallique et la riche cape en velours.\nImage ratio : 2/3."
},
    {
    "title": "PORTRAIT ÉDITORIAL CINÉMATOGRAPHIQUE",
    "styles": "femme fashion cinématique",
    "img": [
        "Images/IMG_20260329_212936.png"
    ],
    "prompt": "Un portrait éditorial cinématographique et de haute couture d’une femme sophistiquée appuyée contre une rampe en bois sur un yacht de luxe vintage au coucher du soleil. Elle porte un chapeau architectural noir avant-gardiste à large bord avec des textures en maille transparente et un\nnœud structurel. Sa tenue est une robe de haute couture en dentelle noire complexe avec un profond décolleté en V et des manches bouffantes. Elle est ornée d’un collier ras de cou en diamant et perle orné et de boucles d’oreilles assorties.\nÉclairage et atmosphère : La lumière du soleil douce et dorée se reflétant sur les vagues de l’océan en arrière-plan, créant une lueur chaude sur sa peau et une lumière de contour subtile.\nDes ombres profondes et sombres soulignent les textures de la dentelle et de la soie.\nDétails techniques : Tourné sur un film de 35 mm, faible profondeur de champ avec un arrière-plan marin flou, gradation des couleurs riche avec des tons chauds et des ombres aux tons turquoise, résolution de 8k, textures de tissus très détaillées, composition élégante et posée.\n\n• Style de la mode : Utilisez des termes comme Haute Couture, Avant-garde et d’inspiration édouardienne pour maintenir ce look de luxe dramatique et historique.\n• Le chapeau : Des mots-clés comme Large-brimmed, Architectural et Tulle sont essentiels pour cette silhouette de couvre-chef spécifique.\n• Le cadre : Mentionner un yacht vintage ou un paquebot fournit l’éclairage intérieur étroit et doré vu sur la photo.\n• Palette de couleurs : Spécifiez l’or muet, les noirs profonds et les larmes d’océan pour obtenir ce niveau de couleur cinématographique spécifique.\nImage ratio : 2/3."
},
    {
    "title": "PORTRAIT DECOLLETE",
    "styles": "femme fashion portrait",
    "img": [
        "Images/13318.png"
    ],
    "prompt": "Créez un portrait en gros plan hyper réaliste d’une femme, utilisez la photo jointe comme référence, en regardant dans l’objectif. Elle porte une robe noire élaborée avec un décolleté plongeant. Le col haut et les revers sont richement ornés de broderies dorées complexes et de perles à motifs floraux. Elle a une coiffure élégante en chignon et est ornée de longues boucles d’oreilles en or étincelantes. Un fermoir décoratif en or avec des chaînes suspendues et un charme céleste accentue le devant de sa robe. Le fond est d’un gris doux et atténué.\nImage ratio : 2/3."
},
    {
    "title": "FEMME FASHION LUXE",
    "styles": "femme fashion ",
    "img": [
        "Images/13315.png"
    ],
    "prompt": "Photo de corps entier dans un style éditorial à la mode, capture ultra-réaliste en 8k, prise avec une caméra Canon EOS R5, objectif 85mm f/1.2 L pour une profondeur de champ cinématographique.\nDécor : intérieur luxueux d’un hall d’hôtel haut de gamme, sol en marbre poli avec des reflets doux, murs avec panneaux de bois verticaux et éclairage d’ambiance chaleureux avec des rondelles dorées créant une atmosphère sophistiquée et exclusive.\nModèle : Femme avec de longs cheveux, lisses et d’un éclat intense, disposés avec une rayure centrale. Maquillage professionnel de style \"glam\" avec des contours définis, lèvres en ton nude marron avec une finition mate, yeux marqués avec un contour fumé et cils volumineux.\nVêtement : Robe corset courte en satin noir avec buste structuré et jupe volumineuse de multiples couches de balivernes (style « peplum » dramatique). Le tissu a un éclat satiné premium.\nAccessoires : collier de mailles épais en or avec pendentif cœur central, bracelets empilés en or sur les poignets. Petit sac à main structuré, style matelassé de couleur blanche.\nChaussures : Scarpin à talons haute avec plate-forme (style \"chunky platform\") en cuir verni noir, avec une délicate bande de cheville. Le mannequin porte un pantalon noir translucide.\nPose et angle : Pose de marche dynamique et naturelle, avec un pied légèrement devant l’autre, capturant le mouvement. L’angle de la caméra est frontal, positionné au niveau de la hanche (eye-level légèrement abaissé) pour mettre en valeur la taille et la silhouette du modèle, conférant grandeur et élégance.\nEclairage et humour : éclairage de studio de haute qualité, axé sur le modèle, mettant en valeur la texture des tissus et l’éclat de la peau. Humour luxueux, confiant et contemporain.\nMaintenez les affections du visage et du corps à 100% comme sur l’image. En maintenant la forme du nez, de la bouche et des yeux identique aux images de référence.\nImage ratio : 2/3."
},
    {
    "title": "BATTEUR GUERRIER NORDIQUE",
    "styles": "homme cinematique",
    "img": [
        "Images/13312.png"
    ],
    "prompt": "Un batteur de guerrier nordique cinématographique hyperréaliste dans un moment décisif, annonciateur de guerre, avec un regard puissant et déterminé signalant le début de la bataille. Le guerrier est un combattant nordique barbu et moustachu portant une tenue de guerrier authentique, capturé en mouvement tout en jouant d’un seul tambour de guerre massif. Il utilise deux grands baguettes rembourrées, frappant dans une séquence alternée rythmique avec les deux mains.\nLe tambour est conçu de manière unique : un seul grand tambour central, avec des éléments sculptés en forme de corne sur ses côtés, placé sur un sol acoustique spécialement doublé qui améliore l’impact de chaque coup. Chaque coup est dynamique, montrant un mouvement visible et une force cinématographique.\nDerrière lui se dresse une vaste armée nordique, floue mais imposante, formant une atmosphère de champ de bataille épique. La scène est ultra-cinématographique, dramatique et hyperréaliste, avec un fort contraste d’éclairage et une énergie d’impact au ralenti.\nUtilisez une image de référence pour la structure faciale et la présence du batteur. Toute la composition ressemble au moment exact avant l’éruption de la guerre—mythique, puissante et cinématographique.\nImage ratio : 2/3."
},
    {
    "title": "PORTRAIT CINÉMATOGRAPHIQUE ULTRARÉALISTE",
    "styles": "femme affiche",
    "img": [
        "Images/13309.png"
    ],
    "prompt": "Portrait cinématographique ultra-réaliste de style IMAX d’une 娇 美 形 guerrière en cosplay très détaillé inspiré par une icône des arts martiaux classiques. Elle est capturée dans une position de combat basse et stable, le corps enroulé avec force et élégance. Son expression est intense et concentrée, les yeux vifs et déterminés, avec des marques de bataille subtiles et des imperfections naturelles de la peau ajoutant du réalisme.\nElle porte une tenue de style qipao en soie bleue profonde déchirée avec une broderie dorée complexe, partiellement endommagée par le combat. Le tissu montre des détails ultra-fins—bords effilochés, plis de tension, léger éclat sous la lumière. Sa peau brille de sueur et d’humidité, mettant en évidence la définition musculaire et la texture naturelle. Ses cheveux sont coiffés en chignons jumeaux avec des rubans blancs fluides, légèrement lâches et dynamiques du mouvement.\nLes bracelets en métal à pointes sur les deux poignets attrapent les points forts, ajoutant une esthétique tranchante et dangereuse. Son physique est athlétique mais gracieux, mélangeant puissance et beauté féminine (娇 美 形).\n🌫️ Éclairage et atmosphère enfumée : une fumée et une brume cinématographiques denses remplissent l’environnement, dérivant à travers la scène avec une profondeur stratifiée. Des faisceaux lumineux volumétriques percent la brume, créant des rayons divins dramatiques. Le rétroéclairage bleu frais sépare sa silhouette de l’arrière-plan, tandis qu’une lumière directionnelle chaude et directionnelle venant du dessus/devant sculpte son visage et son corps. La fumée capte magnifiquement la lumière, produisant une diffusion douce, des bords brillants et une brume cinématographique. Des particules subtiles flottent dans l’air, améliorant le réalisme.\n🏚️ Environnement : Une arène de combat souterraine sombre et abandonnée ou un dojo en ruine. L’arrière-plan est partiellement obscurci par une épaisse fumée et un brouillard, avec de faibles silhouettes d’ennemis à peine visibles à travers la brume. Les surfaces mouillées du sol reflètent une lumière faible, ajoutant à l’atmosphère rugueuse.\n📷 Appareil photo et composition : perspective IMAX à faible angle, faible profondeur de champ. Mise au point ultra-nette sur le sujet avec flou d’arrière-plan cinématographique. Les couches de fumée créent une séparation en profondeur (brume de premier plan, sujet au milieu du sol, silhouettes d’arrière-plan). Un léger flou de mouvement sur des figures éloignées améliore l’intensité de l’action.\nPrise de vue : Plein pied.\n🎨 Style Tags : ultra-réaliste, IMAX amélioré, éclairage cinématographique, atmosphère enfumée, brouillard volumétrique, contraste dramatique, détail 8K, texture de peau hyper-réelle, action freeze frame, chef-d’œuvre, qualité photo du film.\nImage ratio : 2/3."
},
    {
    "title": "JOUEUR FOOTBALL D’ÉLITE",
    "styles": "homme sport affiche",
    "img": [
        "Images/13306.png"
    ],
    "prompt": "Un joueur de football d’élite avec de la terre sur le visage et une expression intense, frappant la balle avec une puissance explosive, capturé dans une prise de vue en contre-plongée depuis le sol, prise sur ARRI Alexa 65, objectif 24 mm, photographie sportive cinématographique, sujet en netteté avec flou de mouvement dynamique, éclairage dramatique du stade, étalonnage cinématographique des couleurs dans les tons sarcelle et orange, composition de héros, style publicitaire sportif haut de gamme, ultra réaliste, 8k. Image ratio : 2/3."
},
    {
        "title": "CINEMATIC",
        "styles": "portrait caricature femme",
        "img": [
            "Images/Gemini_Generated_Image_44306f44306f4430.png",
            "Images/10688.png",
            "Images/10729.png"
        ],
        "prompt": "Créez un portrait caricatural 3D exagéré et stylisé à partir de la personne figurant sur la photo de référence ci-jointe. Conservez l'identité du sujet, les traits de son visage, son teint et ses caractéristiques distinctives, mais réinterprète-les sous la forme d'une caricature 3D audacieuse.\nAppliquez une déformation forte et intentionnelle, notamment un cou allongé, un rapport tête-cou surdimensionné, des paupières tombantes, des lèvres épaisses et une asymétrie faciale subtile. Le personnage doit rester humain tout en étant clairement stylisé et expressif.\nUtilisez une finition de surface propre et contrôlée avec une peau lisse de qualité studio. Évitez les textures aléatoires, les imperfections, les taches de rousseur, la saleté, le grain, les mouchetures ou le bruit. Les matériaux doivent paraître polis, haut de gamme et soigneusement conçus, avec une diffusion subtile sous la surface et un ombrage réaliste de la peau.\nHabillez le personnage avec des vêtements de luxe et des accessoires audacieux et haut de gamme, créant ainsi une esthétique étrange, avant-gardiste et collectionnable qui semble dictée par le personnage plutôt que mignonne ou réaliste.\nÉclairez la scène avec un éclairage de studio neutre, des ombres douces et diffuses, et un éclairage uniforme sans contraste marqué. Utilisez un fond gris neutre uni ou blanc cassé.\nEffectuez le rendu en qualité 4K ultra haute définition avec des détails extrêmes, une mise au point nette et une clarté cinématographique. Incluez des détails de micro-surface, des textures haute résolution, un rendu physique (PBR), un éclairage global, des reflets doux et une définition raffinée des matériaux. L'image doit être nette, propre et sans bruit, avec une qualité de rendu professionnelle en studio.\nPas de texte, de logos ou de filigranes.\nFormat d'image : 2/3."
    },
    {
        "title": "PORTRAIT",
        "styles": "portrait cinematique femme",
        "img": [
            "https://nouchi18.github.io/Mes_Prompts/Images/10683.png"
        ],
        "prompt": "Description Générale : Photographie de mode éditoriale, esthétique glamour et luxueuse, mettant en scène une jeune femme dans une boutique de luxe minimaliste.\n\n1. Sujet & Apparence\nModèle : Jeune femme à la posture élégante et assurée. Cheveux longs, châtains, coiffés en ondulations \"Hollywood Waves\" avec une raie prononcée à droite.\n\nMake-up : Maquillage sophistiqué de type \"Glam Look\". Teint parfait, regard défini (smoky léger), et lèvres finies en vin mat profond.\n\nVisage : [CONSERVER LES TRAITS ORIGINAUX DU VISAGE - NE PAS MODIFIER].\n\n2. Tenue & Accessoires\nVêtement : Mini-robe bustier (strapless) entièrement recouverte de sequins rouges scintillants. Bustier ajusté et jupe structurée à volants superposés pour un effet de volume et de texture.\n\nBijoux : Ensemble de bijoux \"statement\" en argent poli. Choker à maillons épais de style industriel-luxe, bracelets manchettes assortis sur les deux poignets.\n\nAccessoire phare : Sac à main de luxe au premier plan, cuir rouge cerise brillant, motif surpiqué cannage iconique, avec charms métalliques polis suspendus à la poignée.\n\n3. Environnement & Composition\nDécor : Intérieur de boutique de luxe minimaliste. Sol en marbre de Carrare blanc poli avec reflets spéculaires.\n\nProfondeur de champ : Arrière-plan avec présentoirs flous (bokeh artistique) pour créer une isolation du sujet et une sensation d'espace haut de gamme.\n\nCadrage : Plan moyen (medium shot) mettant l'accent sur la silhouette et les accessoires.\n\n4. Éclairage & Technique\nLumière : Éclairage de studio de mode, doux et frontal (type \"Beauty Dish\"). Accentuation des hautes lumières sur les sequins pour créer du scintillement.\n\nQualité d'image : Haute définition, grain de peau photoréaliste, rendu 8K, texture de tissu détaillée.\n\nStyle visuel : Esthétique Vogue / Harper’s Bazaar.\n\n5. Paramètres Techniques\nFormat de l'image : 2:3.\n\nNégatif prompt conseillé : (déformations, traits du visage modifiés, flou de bougé, mauvaise anatomie)."
    },
    {
        "title": "PORTRAIT SPORT",
        "styles": "portrait sport femme",
        "img": [
            "Images/10688.png"
        ],
        "prompt": "Description Générale : Photographie de sport d'élite capturant un instant de triomphe absolu lors d'une finale européenne. 👤 Sujet & Portrait Personnage : Femme athlète à la musculature définie, expression de joie extatique, sourire authentique et émotionnel. Référence Visuelle : Utiliser l'image source pour la structure faciale et les traits distinctifs (Face Match). Détails de la Peau : Texture de peau ultra-détaillée (pores visibles), perles de sueur réalistes, légères traces de terre et d'herbe sur les bras et le visage. Posture : Dynamisme \"action-freeze\", bras levés en V, célébration iconique. 👕 Tenue & Équipement Maillot : Kit domicile officiel du Real Madrid (blanc pur avec finitions dorées). Détails Techniques : Texture de tissu respirant (mesh), blason du club brodé en relief, logo Adidas précis, plis naturels dus au mouvement. 🏟️ Scène & Environnement Contexte : Pelouse luxuriante d'un stade de renommée mondiale, perspective au niveau du sol. Arrière-plan : Coéquipiers en mouvement (flou cinétique), foule en liesse créant un bokeh crémeux. Éléments Particulaires : Pluie fine rétroéclairée, confettis dorés et blancs flottant dans l'air, brume de stade légère. 💡 Éclairage & Atmosphère Style Lumineux : Éclairage de stade dramatique, contre-jour puissant créant un Rim Light (halo de lumière) sur les contours du sujet. Ambiance : Héroïque, cinématographique, intensité d'une finale de Ligue des Champions. Couleurs : Étalonnage type documentaire sportif haut de gamme, contraste élevé, blancs éclatants et verts profonds. ⚙️ Paramètres Techniques (DSLR) Objectif : Téléobjectif 85mm (idéal pour le portrait sportif). Ouverture : f/1.8 (faible profondeur de champ, isolation parfaite du sujet). Rendu : Plage dynamique élevée (HDR), piqué d'image chirurgical (sharp focus), 8K, photoréalisme absolu. Format d'image : Aspect Ratio 2:3 (--ar 2:3)."
    },
    {
        "title": "PORTRAIT FASHION CHAT",
        "styles": "portrait fashion homme",
        "img": [
            "Images/10701.png"
        ],
        "prompt": "🏷️ Sujet & Personnages\nModèle : Mannequin homme à l'allure élégante et charismatique. Teint de peau impeccable, pose confiante et statutaire.\nAttitude : Le mannequin caresse doucement la tête d'un chat géant avec une main délicatement posée sur son cou, exprimant un mélange de puissance souveraine et de tendresse émotionnelle.\nLe Compagnon : Un chat noir colossal aux proportions de panthère majestueuse. Pelage de jais profond, yeux perçants, posture calme et protectrice.\n👗 Garde-robe & Style (Stylisme)\nTenue : Costume long sur mesure de couleur Rouge Cerise, incluant un manteau allongé à la structure nette (sharp tailoring) et à la fluidité élégante. Tissu premium présentant des reflets satinés subtils.\nAccessoires : Lunettes de soleil rectangulaires opaques de couleur cerise assorties, renforçant l'esthétique monochrome audacieuse.\nEsthétique : Look monochrome d'avant-garde, luxe minimaliste.\n🌲 Environnement & Scène (Set Design)\nArrière-plan : Forêt surréaliste composée d'arbres géants stylisés aux feuilles rouge cramoisi massif.\nSol : Texture de sol en velours rouge profond, créant une continuité organique avec le décor.\nAtmosphère : Profondeur atmosphérique avec une légère brume (haze) pour séparer les plans.\n💡 Éclairage & Optique\nLumière : Éclairage directionnel doux de type \"Key Light\" sur les sujets. Utilisation d'une Rim Light (lumière de contour) subtile pour détacher les silhouettes noires et rouges du fond cramoisi.\nOmbres : \"Soft falloff\" (dégradé d'ombres doux) pour un rendu cinématographique.\nObjectif : Rendu moyen format (Phase One/Hasselblad), faible profondeur de champ (f/2.8) pour un bokeh crémeux sur la forêt.\n📸 Spécifications Techniques\nFormat d'image : 2/3\nStyle : Photographie éditoriale de mode, campagne de luxe haute couture.\nRendu : Textures ultra-détaillées (grain du tissu, pelage du chat), étalonnage colorimétrique cinématographique (color grading), 8k, photoréalisme riche."
    },
    {
        "title": "PORTRAIT CAMOMILLE",
        "styles": "portrait femme",
        "img": [
            "Images/10729.png"
        ],
        "prompt": "Directives Générales : Générer une image haute fidélité en conservant une cohérence stricte avec les traits du visage et l'identité de l'image de référence fournie.\n👤 Sujet et Pose\nPersonnage : Une femme éblouissante avec une coupe au carré (bob cut) moderne, déstructurée et texturée.\nAction : Capturée en plein élan, courant avec dynamisme à travers un champ dense de camomilles.\nAngle de vue : Vue de dos (three-quarter back view). Elle tourne la tête par-dessus son épaule vers l'objectif dans un mouvement fluide.\nExpression : Sourire radieux et spontané, regard pétillant, capturant un instant de pure joie et de liberté.\nTenue : Une robe d'été légère qui flotte et ondule sous l'effet de la course et du vent.\n🌿 Environnement et Atmosphère\nScène : Un champ de camomilles à perte de vue, fleurs blanches et cœurs jaunes créant un tapis floral texturé.\nMétéo : Chaleur estivale palpable, atmosphère vaporeuse et romantique.\nDynamique : Effet de vent prononcé dans les cheveux et dans le tissu de la robe pour accentuer le mouvement.\n💡 Éclairage et Colorimétrie\nLumière : \"Golden Hour\" (Heure dorée) intense. Rétroéclairage (backlighting) créant un halo lumineux autour de la silhouette et des cheveux (rim light).\nTeintes : Palettes chaudes, tons ambrés, dorés et orangés contrastant avec le blanc pur des fleurs.\nRendu : Flare d'objectif subtil (lens flare) pour renforcer le côté naturel et cinématographique.\n📸 Paramètres Techniques (Rendu Photographique)\nAppareil : Canon EOS R5, rendu plein format (Full Frame).\nObjectif : 50mm f/1.8 (focale fixe standard pour un rendu naturel).\nProfondeur de champ : Très faible (bokeh prononcé), l'arrière-plan floral est artistiquement flouté pour isoler le sujet.\nExposition : Vitesse d'obturation rapide (1/1000s) pour figer le mouvement des fleurs et des cheveux avec une netteté cristalline. ISO 100 pour une absence totale de grain numérique.\n🖼️ Format et Style\nFormat d'image : Aspect Ratio 2:3 (Portrait vertical).\nStyle visuel : Photographie de mode lifestyle, esthétique cinématographique \"Raw\" (authentique et non retouchée de manière artificielle)."
    },
    {
        "title": "PORTRAIT BIKER CHIC",
        "styles": "portrait femme fashion",
        "img": [
            "Images/8878.png"
        ],
        "prompt": "Sujet et Pose\nModèle : Conserver l'identité faciale originale sans aucune altération des traits.\nPose : Pose dynamique, accroupie (crouching) de profil. Rotation du buste et du cou pour un regard intense \"par-dessus l'épaule\" dirigé vers l'objectif.\nCheveux : Coiffure \"Blond Cendré\" (Ash Blonde), longues boucles volumineuses, texture \"beachy waves\" ébouriffée tombant en cascade sur le dos.\nScène et Stylisme\nStyle : Fusion \"Biker Chic\" structurel et \"Parisian Chic\" minimaliste. Esthétique avant-gardiste et éditoriale.\nTenue : Blazer blanc structuré oversize à épaulettes marquées (power shoulders), cintré par une large ceinture corset blanche assortie.\nBas : Collants blancs transparents (sheer) montant jusqu'aux cuisses (thigh-high), esprit haute couture.\nChaussures : Escarpins blancs classiques à bout pointu (stiletto pumps).\nEnvironnement et Composition\nArrière-plan : Studio professionnel avec mur cyclorama (Cyc-wall) gris mat, sans couture, fini minimaliste.\nCadrage : Composition centrée, sujet net. Utilisation d'un large espace négatif (negative space) pour accentuer la silhouette et l'épure de la scène.\nÉclairage et Colorimétrie\nLumière : Éclairage de studio diffus (softbox large). Présence d'un \"Rim Light\" (éclairage de contour) subtil on la chevelure. Dégradé d'ombres douces (soft drop shadows) sur le sol.\nColorimétrie : Palette de couleurs désaturées (\"muted tones\"), température froide. Blancs éclatants et gris neutres profonds.\nParamètres Techniques (Rendu Photo)\nOptique : Rendu plein format (Full-frame), objectif 85mm f/1.2. Profondeur de champ ultra-courte (shallow depth of field) avec un piqué chirurgical sur le sujet et un flou d'arrière-plan crémeux.\nQualité : Photographie de mode haute résolution, grain de peau naturel, texture textile détaillée, rendu 8k.\nFormat de l'image : 2:3 (Portrait vertical)."
    },
    {
        "title": "PORTRAIT QIPAO LUXE",
        "styles": "portrait femme",
        "img": [
            "Images/8875.png"
        ],
        "prompt": "Sujet & Personnage :\nModèle : Femme élégante à la silhouette voluptueuse et pulpeuse, peau de porcelaine lumineuse et grain de peau ultra-détaillé.\nExpression : Regard confiant, charismatique et séduisant dirigé vers l'objectif.\nMaquillage : Glamour sophistiqué, rouge à lèvres carmin vibrant, paupières rehaussées de micro-paillettes dorées scintillantes.\nCoiffure : Chignons doubles (odango) stylisés avec précision, ornés de bijoux de tête en or et de pompons en soie rouge.\nGarde-robe & Accessoires :\nTenue : Cheongsam (Qipao) traditionnel en soie de mûrier rouge intense. Broderies artisanales complexes en fils d'or et champagne. Texture satinée haut de gamme avec reflets spéculaires réalistes.\nAccessoire : Éventail pliant rouge de luxe avec monture en bois laqué et détails dorés fins, tenu avec grâce.\nEnvironnement & Composition :\nScène : Intérieur luxueux célébrant le Nouvel An Lunaire. Arrière-plan composé de branches de cerisiers en fleurs et de lanternes rouges suspendues.\nÉléments de décor : Table en bois de rose au premier plan (flou d'amorce) avec un bol en céramique fine contenant des mandarines éclatantes.\nComposition : Portrait de mode type \"Editorial Magazine\", cadrage vertical, mise au point sélective sur le visage et les détails de la soie.\nTechniques d'Image & Éclairage :\nÉclairage : Éclairage cinématographique \"Clair-obscur\" chaleureux. Lumière de contour (rim light) dorée pour détacher la silhouette. Bokeh sphérique doux créé par les lanternes.\nOptique : Objectif 85mm f/1.2, profondeur de champ extrêmement réduite (shallow depth of field).\nRendu : Ultra-réaliste, photoréalisme 8K, texture 4K, netteté chirurgicale sur les yeux et les broderies, rendu Octane, esthétique Vogue.\nFormat de l'image : 2:3 (Portrait vertical)"
    },
    {
        "title": "PORTRAIT DENIM ÉDITO",
        "styles": "portrait femme fashion",
        "img": [
            "Images/8873.png"
        ],
        "prompt": "## Sujet et Portrait\nIdentité : Photographie de mode haut de gamme (High-End Fashion). Conservation stricte de l’identité visuelle de la femme de l’image de référence (traits faciaux exacts).\nAttributs : Expression sereine et calme, lèvres dessinées avec un rouge à lèvres mat profond, longs cheveux lisses et raides (sleek hair).\nTenue : Body bustier (sans bretelles) couleur nude-brun avec dos partiellement dénudé, associé à un jean droit en denim bleu moyen (medium wash).\nAccessoires : Grandes boucles d'oreilles vintage argentées, texture métallique réfléchissante.\n## Pose et Composition\nPose : Assise pieds nus sur le sol. Main gauche en appui vers l'arrière, une jambe repliée avec élégance et l'autre allongée vers l'avant. Silhouette fluide et décontractée.\nCadrage : Plan moyen (Medium Shot) capturant l'intégralité du corps et l'espace environnant.\nDécor : Studio minimaliste, environnement \"Pure White\" immaculé, esthétique épurée et vide (negative space).\n## Éclairage et Style Visuel\nType de Lumière : Éclairage latéral directionnel intense (Hard Side Lighting).\nEffets d'Ombre : Ombres portées géométriques nettes et contrastées (Sharp Shadows) se projetant sur le sol et le mur arrière.\nRendu : Esthétique éditoriale moderne, grain de peau naturel et détaillé (Skin Texture), rendu photoréaliste haute définition.\nCouleurs : Palette minimaliste dominée par le blanc, le denim bleu et le nude, accentuée par le rouge des lèvres.\n## Paramètres Techniques\nFormat de l'image : 2:3 (Portrait)\nStyle : Photographie professionnelle au format 35mm, profondeur de champ subtile."
    },
    {
        "title": "PORTRAIT ROUGE CHIAROSCURO",
        "styles": "portrait femme fashion",
        "img": [
            "Images/8872.png"
        ],
        "prompt": "Instructions Principales :\nGénérer une photographie ultra-réaliste combinant un portrait en gros plan et une vue en pied (full-body shot). Respecter strictement les traits du visage de l'image de référence fournie.\n👤 Sujet & Portrait\nModèle : Femme à la silhouette voluptueuse et pulpeuse, posture audacieuse et confiante.\nVisage & Expression : Expression provocante, regard intense. Détails de la peau hyper-réalistes (pores visibles, grain de peau naturel, teint éclatant/dewy).\nChevelure : Cheveux ondulés texturés tombant en cascade sur les épaules.\nPose : Légèrement penchée contre un tabouret de bar, jambes croisées, une main posée avec assurance sur la cuisse.\n👗 Garde-robe & Accessoires\nTenue : Mini-robe rouge ajustée, motifs floraux complexes et brodés, décolleté élégant, fentes latérales hautes jusqu'aux hanches.\nAccessoires : Collier ras-du-cou en or fin, boucles d'oreilles pendantes assorties en or poli.\nChaussures : Escarpins à talons aiguilles noirs vernis (stilettos).\n🏛️ Scénographie & Environnement\nLieu : Salon d'un hôtel de luxe (lounge haut de gamme).\nDécor : Sol en marbre sombre veiné, accents décoratifs dorés, pétales de rose parsemés au sol.\nAmbiance : Atmosphère intime, feutrée et sophistiquée.\n💡 Éclairage & Rendu Visuel\nType d'éclairage : Éclairage \"Chiaroscuro\" (clair-obscur) dramatique et discret (low-key lighting).\nSources : Lueur douce de bougies vacillantes et appliques murales chaleureuses créant des ombres portées intimes.\nTechnique : Rendu photoréaliste 8k, haute plage dynamique (HDR), profondeur de champ cinématique (bokeh léger en arrière-plan).\n📐 Spécifications Techniques\nFormat d'image (Aspect Ratio) : 2/3\nStyle : Photographie de mode commerciale / Éditorial luxe.\nFinition : Netteté extrême sur les textures textiles et les bijoux."
    },
    {
        "title": "PORTRAIT BARBIECORE 60S",
        "styles": "femme fashion",
        "img": [
            "Images/8881.png"
        ],
        "prompt": "Sujet & Modèle :\nPersonnage : Femme élégante au look \"Barbiecore\" vintage.\nPose : Assise de manière dynamique dans un fauteuil, dos incliné vers l'arrière, jambes relevées et allongées, chevilles délicatement croisées.\nExpression : Regard direct vers l'objectif, expression de surprise espiègle (playful surprise), bouche légèrement entrouverte.\nGarde-robe & Stylisme (Fashion Editorial) :\nHaut : Chemisier blanc impeccable à manches bouffantes volumineuses et poignets structurés, surmonté d'un corset rose à motifs ornementaux.\nBas : Collants blancs opaques épais, escarpins à talons ornés de plumes roses vaporeuses.\nAccessoires : Multiples rangs de colliers de perles classiques.\nCoiffure : Style rétro des années 60, volume généreux, grosses boucles structurées avec des bigoudis roses apparents intégrés à la coiffure.\nObjet : Téléphone à cadran vintage blanc avec finitions dorées luxueuses.\nCadre & Décor (Scène) :\nMobilier : Fauteuil pivotant rond en velours rose poudré, texture douce et luxueuse.\nEnvironnement : Studio minimaliste, mur de fond rose vif (Hot Pink) parfaitement lisse, sans texture, créant une esthétique monochrome saturée.\nTechnique Photographique & Éclairage :\nCadrage : Plan en pied (Full body shot), angle de vue en légère contre-plongée (low angle) pour magnifier la silhouette.\nÉclairage : Lumière de studio frontale, douce et enveloppante (high-key lighting), aucune ombre portée dure, rendu \"beauté\" parfaitement uniforme.\nOptique : Rendu net, lignes épurées, style éditorial de magazine de mode haute couture.\nAtmosphère & Colorimétrie :\nStyle : Rétro-glamour des années 60, esthétique publicitaire vintage, mélange d'humour et de sophistication.\nCouleurs : Palette de dégradés de roses saturés, blancs éclatants et touches dorées. Correction colorimétrique vibrante et brillante (glossy finish).\nFormat de l'image : 2:3"
    },
    {
        "title": "PORTRAIT COQUETTE PREPPY",
        "styles": "portrait femme",
        "img": [
            "Images/8869.png"
        ],
        "prompt": "Description Générale : Portrait éditorial haute couture d'une femme à la silhouette voluptueuse, capturant une esthétique \"Coquette-Preppy\" luxueuse et printanière.\n👤 Sujet & Portrait\nModèle : Femme voluptueuse et pulpeuse, traits faciaux précis et réalistes (respecter l'identité fournie), teint frais.\nCoiffure & Maquillage : Longue chevelure ondulée (beach waves) avec du mouvement ; maquillage \"soft glam\" naturel, lèvres rosées, grain de peau visible.\nPose : Posture élégante et décontractée, allure de blogueuse mode influente.\n👗 Garde-robe (Stylisme)\nHaut : Cardigan court (cropped) en maille épaisse vert émeraude foncé, texture tricotée détaillée, fermé par trois nœuds délicats en ruban sur le devant, manches longues.\nBas : Jupe midi plissée à taille haute, dégradé (ombre) de rose pâle, tissu en mousseline de soie vaporeuse avec un effet de mouvement aérien.\nAccessoires : * Lunettes de soleil ovales vintage à monture dorée, posées sur la tête, verres teintés rose.\nSac à main de luxe en forme de cœur rose poudré, orné d'un charm miniature vert et doré.\nChaussures : Baskets \"lifestyle\" haut de gamme, coloris blocs rose pastel et vert menthe.\n☕ Scène & Environnement\nLieu : Terrasse d'un café parisien chic ou intérieur de café design avec des touches de marbre et de fleurs.\nComposition : Style \"Pinterest-ready\", cadrage vertical type magazine de mode, profondeur de champ courte (bokeh) pour isoler le sujet de l'arrière-plan.\n💡 Éclairage & Esthétique\nLumière : Éclairage doré d'après-midi (Golden Hour doux), lumière diffuse qui accentue les textures de la maille et la transparence de la soie.\nPalette de couleurs : Contraste riche entre le vert émeraude profond et la douceur des pastels (rose poudré, vert menthe).\nAmbiance : Féminine, romantique, luxueuse, esthétique \"soft-girl\" haut de gamme.\n⚙️ Spécifications Techniques\nModèle : Nano Banana 2 (Gemini 3 Flash Image).\nRésolution : Ultra-haute définition 8K, piqué net (sharp focus), rendu photoréaliste.\nFormat d'image : 2:3 (Aspect Ratio).\nStyle : Editorial Fashion Photography."
    }
];